/**
 * Como a imprensa chama cada empresa listada, para a aba Noticias da ficha.
 *
 * Escrita a mao para as 321 empresas do banco em 24/09/2026, porque nenhuma
 * fonte automatica serve para buscar manchete. O nome comercial da CVM vem
 * desatualizado (KROTON, PETRO RIO, ESTACIO, PONTO FRIO) e o nome de pregao da
 * B3 vem cortado em 12 letras (MAGAZ LUIZA, ITAUUNIBANCO, SID NACIONAL).
 *
 * `tickers` sao todas as classes da empresa, copiadas de `empresa_tickers` --
 * nunca deduzidas pelas 4 primeiras letras (o emissor "EMBR" da B3 e a
 * Embrast, nao a Embraer).
 *
 * `ambiguo`: o nome e palavra comum ou marca global (Light, Rumo, Tenda,
 * Santander, Whirlpool). Sem o ticker na manchete, so conta imprensa
 * financeira -- e o que mantem a aba sobre financas.
 *
 * `naoE`: expressoes com o nome que nao sao a empresa ("Vale do Paraiba",
 * "Area Azul", "Itau BBA" falando de outra acao).
 *
 * Empresa sem nome (`nomes: []`) e buscada so pelo ticker: o nome dela e comum
 * demais para a busca (B3, que aparece em toda manchete de bolsa) ou a
 * imprensa so a cita com o ticker junto.
 *
 * Empresa nova da carga semanal da B3 nao esta aqui: a rota busca so pelo
 * ticker e avisa no log, para a linha ser acrescentada.
 */

import type { Identidade } from "./noticias";

export type EmpresaNaImprensa = {
  tickers: string[];
  nomes: string[];
  ambiguo?: true;
  naoE?: RegExp[];
};

export const EMPRESAS: EmpresaNaImprensa[] = [
  { tickers: ["AALR3"], nomes: ["Alliar"] },
  { tickers: ["ABCB4"], nomes: ["ABC Brasil", "Banco ABC"] },
  { tickers: ["ABEV3"], nomes: ["Ambev"] },
  { tickers: ["ADMF3", "B1003"], nomes: ["B100"], ambiguo: true },
  { tickers: ["AERI3"], nomes: ["Aeris"] },
  { tickers: ["AFLT3"], nomes: ["Afluente"] },
  { tickers: ["AGRO3"], nomes: ["BrasilAgro"] },
  { tickers: ["AHEB3", "AHEB5", "AHEB6"], nomes: ["SPTuris"] },
  { tickers: ["ALLD3"], nomes: ["Allied"] },
  { tickers: ["ALOS3"], nomes: ["Allos"], ambiguo: true },
  { tickers: ["ALPA3", "ALPA4"], nomes: ["Alpargatas"] },
  { tickers: ["ALPK3"], nomes: ["Estapar"] },
  { tickers: ["ALUP11", "ALUP3", "ALUP4"], nomes: ["Alupar"] },
  { tickers: ["AMAR3"], nomes: ["Marisa", "Lojas Marisa"], ambiguo: true },
  { tickers: ["AMBP3"], nomes: ["Ambipar"] },
  { tickers: ["AMOB3"], nomes: ["Automob"] },
  { tickers: ["ANIM3"], nomes: ["Ânima Educação", "Ânima Holding"] },
  { tickers: ["ARML3"], nomes: ["Armac"] },
  { tickers: ["ARND3", "NINJ3"], nomes: ["Arandu", "GetNinjas"], ambiguo: true },
  { tickers: ["ASAI3"], nomes: ["Assaí"] },
  { tickers: ["ATED3"], nomes: ["Atom Educação"] },
  { tickers: ["AUAU3"], nomes: ["Petz Cobasi", "União Pet"] },
  { tickers: ["AURE3"], nomes: ["Auren"], ambiguo: true },
  { tickers: ["AVLL3"], nomes: ["Alphaville Urbanismo"] },
  { tickers: ["AXIA3", "AXIA7", "ELET3", "ELET5", "ELET6"], nomes: ["Axia Energia", "Eletrobras", "Axia"], ambiguo: true },
  { tickers: ["AZEV3", "AZEV4"], nomes: ["Azevedo & Travassos"] },
  { tickers: ["AZTE3"], nomes: ["AZT Energia"] },
  { tickers: ["AZUL3", "AZUL4", "AZUL97", "AZUL98", "AZUL99"], nomes: ["Azul"], ambiguo: true, naoE: [/\b(Área|Zona|Setembro|Outubro|Novembro|Economia|Fita|Serra|Máfia) Azul\b/, /\bAzul (Fidelidade|Viagens)\b/] },
  { tickers: ["AZZA3"], nomes: ["Azzas 2154", "Azzas"] },
  { tickers: ["B3SA3"], nomes: [] },
  { tickers: ["BALM3", "BALM4"], nomes: ["Baumer"] },
  { tickers: ["BAUH4"], nomes: ["Excelsior Alimentos"], ambiguo: true },
  { tickers: ["BAZA3"], nomes: ["Banco da Amazônia", "Basa"] },
  { tickers: ["BBAS3"], nomes: ["Banco do Brasil"] },
  { tickers: ["BBDC3", "BBDC4"], nomes: ["Bradesco"], naoE: [/\bBradesco BBI\b/] },
  { tickers: ["BBSE3"], nomes: ["BB Seguridade"] },
  { tickers: ["BEEF3"], nomes: ["Minerva Foods", "Minerva"], ambiguo: true },
  { tickers: ["BEES3", "BEES4"], nomes: ["Banestes"] },
  { tickers: ["BGIP3", "BGIP4"], nomes: ["Banese"] },
  { tickers: ["BHIA3"], nomes: ["Casas Bahia"], ambiguo: true },
  { tickers: ["BIED3"], nomes: ["Bioma Educação"] },
  { tickers: ["BIOM3"], nomes: ["Biomm"] },
  { tickers: ["BLAU3"], nomes: ["Blau Farmacêutica"], ambiguo: true },
  { tickers: ["BMEB3", "BMEB4"], nomes: ["Banco Mercantil"], ambiguo: true },
  { tickers: ["BMGB4"], nomes: ["Banco BMG", "BMG"] },
  { tickers: ["BMIN3", "BMIN4"], nomes: ["Mercantil Investimentos"], ambiguo: true },
  { tickers: ["BMKS3"], nomes: ["Monark", "Bicicletas Monark"], ambiguo: true },
  { tickers: ["BMOB3"], nomes: ["Bemobi"] },
  { tickers: ["BNBR3"], nomes: ["Banco do Nordeste", "BNB"] },
  { tickers: ["BOBR4"], nomes: ["Bombril"] },
  { tickers: ["BPAC11", "BPAC3", "BPAC5"], nomes: ["BTG Pactual"] },
  { tickers: ["BPAN4"], nomes: ["Banco Pan"], ambiguo: true },
  { tickers: ["BPAR3"], nomes: ["Banpará"] },
  { tickers: ["BRAP3", "BRAP4"], nomes: ["Bradespar"] },
  { tickers: ["BRAV3"], nomes: ["Brava Energia", "Brava"], ambiguo: true },
  { tickers: ["BRBI11"], nomes: ["BR Partners"] },
  { tickers: ["BRFS3"], nomes: ["BRF"] },
  { tickers: ["BRKM3", "BRKM5", "BRKM6"], nomes: ["Braskem"] },
  { tickers: ["BRSR3", "BRSR5", "BRSR6"], nomes: ["Banrisul"] },
  { tickers: ["BRST3"], nomes: ["Brisanet"] },
  { tickers: ["BSLI3", "BSLI4"], nomes: ["BRB", "Banco de Brasília"] },
  { tickers: ["CALI3"], nomes: ["Construtora Adolpho Lindenberg"] },
  { tickers: ["CAMB3"], nomes: ["Cambuci"], ambiguo: true },
  { tickers: ["CAML3"], nomes: ["Camil"] },
  { tickers: ["CASH3"], nomes: ["Méliuz"] },
  { tickers: ["CBAV3"], nomes: ["CBA", "Companhia Brasileira de Alumínio"] },
  { tickers: ["CBEE3"], nomes: ["Ampla Energia"], ambiguo: true },
  { tickers: ["CCRO3", "MOTV3"], nomes: ["Motiva", "CCR"], ambiguo: true },
  { tickers: ["CCTY3"], nomes: ["RDVC City"] },
  { tickers: ["CEAB3"], nomes: ["C&A"] },
  { tickers: ["CEBR3", "CEBR5", "CEBR6"], nomes: ["CEB", "Neoenergia Brasília"], ambiguo: true },
  { tickers: ["CEDO3", "CEDO4"], nomes: ["Cedro Têxtil", "Cedro Cachoeira"], ambiguo: true },
  { tickers: ["CEEB3", "CEEB5"], nomes: ["Coelba"] },
  { tickers: ["CEED3"], nomes: ["CEEE-D", "CEEE Equatorial"] },
  { tickers: ["CEGR3"], nomes: ["Naturgy", "CEG"], ambiguo: true },
  { tickers: ["CGAS3", "CGAS5"], nomes: ["Comgás"] },
  { tickers: ["CGRA3", "CGRA4"], nomes: ["Grazziotin"] },
  { tickers: ["CLSA3"], nomes: ["ClearSale"] },
  { tickers: ["CLSC3", "CLSC4"], nomes: ["Celesc"] },
  { tickers: ["CMIG3", "CMIG4"], nomes: ["Cemig"] },
  { tickers: ["CMIN3"], nomes: ["CSN Mineração"] },
  { tickers: ["COCE3", "COCE5"], nomes: ["Coelce", "Enel Ceará"] },
  { tickers: ["COGN3"], nomes: ["Cogna", "Kroton"] },
  { tickers: ["CPFE3"], nomes: ["CPFL Energia", "CPFL"] },
  { tickers: ["CPLE3", "CPLE5", "CPLE6"], nomes: ["Copel"] },
  { tickers: ["CRFB3"], nomes: ["Carrefour Brasil", "Atacadão", "Grupo Carrefour Brasil"], ambiguo: true },
  { tickers: ["CRPG3", "CRPG5", "CRPG6"], nomes: ["Tronox Pigmentos", "Cristal Pigmentos"], ambiguo: true },
  { tickers: ["CSAN3"], nomes: ["Cosan"] },
  { tickers: ["CSED3"], nomes: ["Cruzeiro do Sul Educacional"] },
  { tickers: ["CSMG3"], nomes: ["Copasa"] },
  { tickers: ["CSNA3"], nomes: ["CSN", "Companhia Siderúrgica Nacional"] },
  { tickers: ["CSUD3"], nomes: ["CSU Digital", "CSU"] },
  { tickers: ["CTKA3", "CTKA4"], nomes: ["Karsten"] },
  { tickers: ["CURY3"], nomes: ["Cury Construtora", "Cury"], ambiguo: true },
  { tickers: ["CVCB3"], nomes: ["CVC Corp", "CVC"], ambiguo: true },
  { tickers: ["CXSE3"], nomes: ["Caixa Seguridade"] },
  { tickers: ["CYRE3", "CYRE4"], nomes: ["Cyrela"] },
  { tickers: ["DASA3"], nomes: ["Dasa"], ambiguo: true },
  { tickers: ["DESK3"], nomes: ["Desktop S.A."], ambiguo: true },
  { tickers: ["DEXP3", "DEXP4"], nomes: ["Dexxos"] },
  { tickers: ["DIRR3"], nomes: ["Direcional Engenharia", "Direcional"], ambiguo: true },
  { tickers: ["DMVF3"], nomes: ["d1000", "d1000 Varejo Farma"] },
  { tickers: ["DOHL3", "DOHL4"], nomes: ["Döhler", "Dohler"] },
  { tickers: ["DOTZ3"], nomes: ["Dotz"] },
  { tickers: ["DTCY3"], nomes: ["Dtcom"] },
  { tickers: ["DXCO3"], nomes: ["Dexco"] },
  { tickers: ["EALT3", "EALT4"], nomes: ["Electro Aço Altona", "Altona"] },
  { tickers: ["ECOM3", "TRAD3"], nomes: ["Economatica", "TC Traders Club"], ambiguo: true },
  { tickers: ["ECOR3"], nomes: ["Ecorodovias"] },
  { tickers: ["EGGY3"], nomes: ["Granja Faria"] },
  { tickers: ["EGIE3"], nomes: ["Engie Brasil", "Engie"], ambiguo: true },
  { tickers: ["EKTR3", "EKTR4"], nomes: ["Elektro"], ambiguo: true },
  { tickers: ["ELMD3"], nomes: ["Eletromidia"] },
  { tickers: ["EMAE3", "EMAE4"], nomes: ["EMAE"] },
  { tickers: ["EMBJ3", "EMBR3"], nomes: ["Embraer"] },
  { tickers: ["ENEV3"], nomes: ["Eneva"] },
  { tickers: ["ENGI11", "ENGI3", "ENGI4"], nomes: ["Energisa"] },
  { tickers: ["ENJU3"], nomes: ["Enjoei"] },
  { tickers: ["ENMT3", "ENMT4"], nomes: ["Energisa Mato Grosso", "Energisa MT"] },
  { tickers: ["EPAR3"], nomes: ["Embpar"] },
  { tickers: ["EQMA3B"], nomes: ["Equatorial Maranhão"] },
  { tickers: ["EQPA3", "EQPA5", "EQPA6", "EQPA7"], nomes: ["Equatorial Pará"] },
  { tickers: ["EQTL3"], nomes: ["Equatorial Energia", "Equatorial"], ambiguo: true },
  { tickers: ["ESPA3"], nomes: ["Espaçolaser"] },
  { tickers: ["ESTR3", "ESTR4"], nomes: ["Brinquedos Estrela"], ambiguo: true },
  { tickers: ["ETER3"], nomes: ["Eternit"] },
  { tickers: ["EUCA3", "EUCA4"], nomes: ["Eucatex"] },
  { tickers: ["EVEN3"], nomes: ["Even Construtora"], ambiguo: true },
  { tickers: ["EZTC3"], nomes: ["EZTec"] },
  { tickers: ["FESA3", "FESA4"], nomes: ["Ferbasa"] },
  { tickers: ["FHER3"], nomes: ["Fertilizantes Heringer", "Heringer"] },
  { tickers: ["FICT3"], nomes: [], ambiguo: true },
  { tickers: ["FIEI3"], nomes: [], ambiguo: true },
  { tickers: ["FIGE3"], nomes: ["Investimentos Bemge"], ambiguo: true },
  { tickers: ["FIQE3"], nomes: ["Unifique"] },
  { tickers: ["FLRY3"], nomes: ["Fleury"], ambiguo: true },
  { tickers: ["FRAS3"], nomes: ["Frasle Mobility", "Fras-le"] },
  { tickers: ["FRIO3"], nomes: ["Metalfrio"] },
  { tickers: ["GEPA3", "GEPA4"], nomes: ["Rio Paranapanema Energia", "Paranapanema"], ambiguo: true },
  { tickers: ["GFSA3"], nomes: ["Gafisa"] },
  { tickers: ["GGBR3", "GGBR4"], nomes: ["Gerdau"] },
  { tickers: ["GGPS3"], nomes: ["Grupo GPS"], ambiguo: true },
  { tickers: ["GMAT3"], nomes: ["Grupo Mateus"] },
  { tickers: ["GOAU3", "GOAU4"], nomes: ["Metalúrgica Gerdau"] },
  { tickers: ["GOLL4", "GOLL54"], nomes: ["Gol Linhas Aéreas", "Gol"], ambiguo: true, naoE: [/\bGol (de|do|da|contra|olímpico|mil)\b/i] },
  { tickers: ["GPAR3"], nomes: ["Celgpar"] },
  { tickers: ["GRND3"], nomes: ["Grendene"] },
  { tickers: ["GSHP3"], nomes: ["General Shopping"] },
  { tickers: ["GUAR3", "RIAA3"], nomes: ["Riachuelo", "Guararapes"], ambiguo: true },
  { tickers: ["HAGA3", "HAGA4"], nomes: ["Haga"], ambiguo: true },
  { tickers: ["HAPV3"], nomes: ["Hapvida"] },
  { tickers: ["HBOR3"], nomes: ["Helbor"] },
  { tickers: ["HBRE3"], nomes: ["HBR Realty"] },
  { tickers: ["HBSA3"], nomes: ["Hidrovias do Brasil"] },
  { tickers: ["HBTS5"], nomes: ["Habitasul"], ambiguo: true },
  { tickers: ["HETA4"], nomes: [], ambiguo: true },
  { tickers: ["HYPE3"], nomes: ["Hypera"] },
  { tickers: ["IFCM3"], nomes: ["Infracommerce"] },
  { tickers: ["IGTI11", "IGTI3", "IGTI4"], nomes: ["Iguatemi"], ambiguo: true },
  { tickers: ["INEP3", "INEP4"], nomes: ["Inepar"] },
  { tickers: ["INTB3"], nomes: ["Intelbras"] },
  { tickers: ["IRBR3"], nomes: ["IRB(Re)", "IRB Brasil RE", "IRB Re"], ambiguo: true },
  { tickers: ["ISAE3", "ISAE4"], nomes: ["ISA Energia", "ISA CTEEP", "CTEEP"] },
  { tickers: ["ITSA3", "ITSA4"], nomes: ["Itaúsa"] },
  { tickers: ["ITUB3", "ITUB4"], nomes: ["Itaú Unibanco", "Itaú"], naoE: [/\bItaú BBA\b/] },
  { tickers: ["JALL3"], nomes: ["Jalles Machado", "Jalles"] },
  { tickers: ["JBSS3"], nomes: ["JBS"] },
  { tickers: ["JHSF3"], nomes: ["JHSF"] },
  { tickers: ["JOPA3", "JOPA4"], nomes: ["Josapar"] },
  { tickers: ["JSLG3"], nomes: ["JSL"] },
  { tickers: ["KEPL3"], nomes: ["Kepler Weber"] },
  { tickers: ["KLBN11", "KLBN3", "KLBN4"], nomes: ["Klabin"] },
  { tickers: ["KRSA3"], nomes: ["Kora Saúde"] },
  { tickers: ["LAND3"], nomes: ["Terra Santa", "TS Agro"], ambiguo: true },
  { tickers: ["LAVV3"], nomes: ["Lavvi"] },
  { tickers: ["LEVE3"], nomes: ["Mahle Metal Leve", "Metal Leve"] },
  { tickers: ["LIGT3"], nomes: ["Light"], ambiguo: true },
  { tickers: ["LIPR3"], nomes: ["Eletropar"] },
  { tickers: ["LJQQ3"], nomes: ["Quero-Quero", "Lojas Quero-Quero"], ambiguo: true },
  { tickers: ["LOGG3"], nomes: ["LOG Commercial Properties", "LOG CP"], ambiguo: true },
  { tickers: ["LOGN3"], nomes: ["Log-In Logística"], ambiguo: true },
  { tickers: ["LPSB3"], nomes: [], ambiguo: true },
  { tickers: ["LREN3"], nomes: ["Lojas Renner", "Renner"] },
  { tickers: ["LUPA3"], nomes: ["Lupatech"] },
  { tickers: ["LUXM4"], nomes: ["Trevisa"], ambiguo: true },
  { tickers: ["LWSA3"], nomes: ["LWSA", "Locaweb"] },
  { tickers: ["MAPT3", "MAPT4"], nomes: ["Cemepe", "Marcopolo"], ambiguo: true },
  { tickers: ["MATD3"], nomes: ["Mater Dei"], ambiguo: true },
  { tickers: ["MBLY3", "TOKY3"], nomes: ["Grupo Toky", "Toky", "Mobly"], ambiguo: true },
  { tickers: ["MBRF3"], nomes: ["MBRF", "Marfrig"] },
  { tickers: ["MDIA3"], nomes: ["M. Dias Branco", "M.Dias Branco", "M Dias Branco"] },
  { tickers: ["MDNE3"], nomes: ["Moura Dubeux"] },
  { tickers: ["MEAL3"], nomes: ["International Meal Company"], ambiguo: true },
  { tickers: ["MELK3"], nomes: ["Melnick"] },
  { tickers: ["MERC3", "MERC4"], nomes: ["Mercantil Financeira"], ambiguo: true },
  { tickers: ["MGEL4"], nomes: ["Mangels"] },
  { tickers: ["MGLU3"], nomes: ["Magazine Luiza", "Magalu"] },
  { tickers: ["MILS3"], nomes: ["Mills"], ambiguo: true },
  { tickers: ["MLAS3"], nomes: ["Multilaser", "Grupo Multi"], ambiguo: true },
  { tickers: ["MMAQ4"], nomes: ["Minasmáquinas"] },
  { tickers: ["MNDL3"], nomes: ["Mundial S.A."], ambiguo: true },
  { tickers: ["MNPR3"], nomes: ["Minupar"] },
  { tickers: ["MOAR3"], nomes: ["Monteiro Aranha"] },
  { tickers: ["MOVI3"], nomes: ["Movida"] },
  { tickers: ["MRSA3B", "MRSA5B", "MRSA6B"], nomes: ["MRS Logística", "MRS"], ambiguo: true },
  { tickers: ["MRVE3"], nomes: ["MRV"] },
  { tickers: ["MSPA3", "MSPA4"], nomes: ["Melhoramentos"], ambiguo: true },
  { tickers: ["MTRE3"], nomes: ["Mitre Realty", "Mitre"], ambiguo: true },
  { tickers: ["MTSA3", "MTSA4"], nomes: ["Metisa"] },
  { tickers: ["MULT3"], nomes: ["Multiplan"] },
  { tickers: ["MWET3", "MWET4"], nomes: ["Wetzel"] },
  { tickers: ["MYPK3"], nomes: ["Iochpe-Maxion"] },
  { tickers: ["NATU3"], nomes: ["Natura"], ambiguo: true },
  { tickers: ["NEOE3"], nomes: ["Neoenergia"] },
  { tickers: ["NGRD3"], nomes: ["Neogrid"] },
  { tickers: ["NORD3"], nomes: ["Nordon"] },
  { tickers: ["NTCO3"], nomes: ["Natura &Co", "Natura"], ambiguo: true },
  { tickers: ["NUTR3"], nomes: ["Nutriplant"] },
  { tickers: ["OBTC3"], nomes: ["OranjeBTC"] },
  { tickers: ["ODPV3", "SAUD3"], nomes: ["Bradsaúde", "Odontoprev"] },
  { tickers: ["OFSA3"], nomes: ["Ourofino"] },
  { tickers: ["ONCO3"], nomes: ["Oncoclínicas"] },
  { tickers: ["OPCT3"], nomes: ["OceanPact"] },
  { tickers: ["ORVR3"], nomes: ["Orizon"] },
  { tickers: ["PASS3"], nomes: ["Compass Gás e Energia", "Compass"], ambiguo: true },
  { tickers: ["PATI3", "PATI4"], nomes: ["Panatlântica"] },
  { tickers: ["PCAR3"], nomes: ["GPA", "Pão de Açúcar"], ambiguo: true },
  { tickers: ["PDGR3"], nomes: ["PDG Realty", "PDG"] },
  { tickers: ["PDTC3"], nomes: ["Padtec"] },
  { tickers: ["PEAB3", "PEAB4"], nomes: ["Aliança da Bahia"] },
  { tickers: ["PETR3", "PETR4"], nomes: ["Petrobras"] },
  { tickers: ["PETZ3"], nomes: ["Petz"] },
  { tickers: ["PFRM3"], nomes: ["Profarma"] },
  { tickers: ["PGMN3"], nomes: ["Pague Menos"] },
  { tickers: ["PINE3", "PINE4"], nomes: ["Banco Pine"], ambiguo: true },
  { tickers: ["PLAS3"], nomes: ["Plascar"] },
  { tickers: ["PLPL3"], nomes: ["Plano & Plano"] },
  { tickers: ["PNVL3"], nomes: ["Panvel", "Dimed"] },
  { tickers: ["POMO3", "POMO4"], nomes: ["Marcopolo"] },
  { tickers: ["PORT3"], nomes: ["Wilson Sons"] },
  { tickers: ["POSI3"], nomes: ["Positivo Tecnologia", "Positivo"], ambiguo: true },
  { tickers: ["PRIO3"], nomes: ["Prio", "PetroRio"], ambiguo: true },
  { tickers: ["PRNR3"], nomes: ["Priner"] },
  { tickers: ["PSSA3"], nomes: ["Porto Seguro"], ambiguo: true },
  { tickers: ["PTBL3"], nomes: ["Portobello"] },
  { tickers: ["PTNT3", "PTNT4"], nomes: ["Pettenati"] },
  { tickers: ["QUAL3"], nomes: ["Qualicorp"] },
  { tickers: ["RADL3"], nomes: ["Raia Drogasil", "RD Saúde"] },
  { tickers: ["RAIL3"], nomes: ["Rumo"], ambiguo: true },
  { tickers: ["RAIZ4"], nomes: ["Raízen"] },
  { tickers: ["RANI3"], nomes: ["Irani"] },
  { tickers: ["RAPT3", "RAPT4"], nomes: ["Randoncorp", "Randon"] },
  { tickers: ["RCSL3", "RCSL4"], nomes: ["Recrusul"] },
  { tickers: ["RDNI3"], nomes: ["RNI", "Rodobens"], ambiguo: true },
  { tickers: ["RDOR3"], nomes: ["Rede D'Or", "Rede D’Or"] },
  { tickers: ["RECV3"], nomes: ["PetroReconcavo", "PetroRecôncavo"] },
  { tickers: ["REDE3"], nomes: ["Rede Energia"], ambiguo: true },
  { tickers: ["RENT3", "RENT4"], nomes: ["Localiza"] },
  { tickers: ["RNEW11", "RNEW3", "RNEW4"], nomes: ["Renova Energia"], ambiguo: true },
  { tickers: ["ROMI3"], nomes: ["Indústrias Romi", "Romi"], ambiguo: true },
  { tickers: ["RPAD3", "RPAD5", "RPAD6"], nomes: ["Alfa Holdings"], ambiguo: true },
  { tickers: ["RSUL4"], nomes: ["Riosulense"] },
  { tickers: ["RVEE3"], nomes: ["Revee"] },
  { tickers: ["SANB11", "SANB3", "SANB4"], nomes: ["Santander Brasil", "Santander"], ambiguo: true },
  { tickers: ["SAPR11", "SAPR3", "SAPR4"], nomes: ["Sanepar"] },
  { tickers: ["SBFG3"], nomes: ["Grupo SBF", "Centauro"], ambiguo: true },
  { tickers: ["SBSP3"], nomes: ["Sabesp"] },
  { tickers: ["SCAR3"], nomes: ["São Carlos Empreendimentos"], ambiguo: true },
  { tickers: ["SEER3"], nomes: ["Ser Educacional"] },
  { tickers: ["SEQL3"], nomes: ["Sequoia Logística", "Sequoia"], ambiguo: true },
  { tickers: ["SHOW3"], nomes: ["T4F", "Time For Fun"] },
  { tickers: ["SHUL4"], nomes: ["Schulz"], ambiguo: true },
  { tickers: ["SIMH3"], nomes: ["Simpar"] },
  { tickers: ["SLCE3"], nomes: ["SLC Agrícola"] },
  { tickers: ["SMFT3"], nomes: ["Smart Fit", "Smartfit"] },
  { tickers: ["SMTO3"], nomes: ["São Martinho"], ambiguo: true },
  { tickers: ["SNSY3", "SNSY5"], nomes: ["Sansuy"] },
  { tickers: ["SOJA3"], nomes: ["Boa Safra"], ambiguo: true },
  { tickers: ["SOND3", "SOND5", "SOND6"], nomes: ["Sondotécnica"] },
  { tickers: ["SRNA3"], nomes: ["Serena Energia", "Serena"], ambiguo: true },
  { tickers: ["SUZB3"], nomes: ["Suzano"] },
  { tickers: ["SYNE3"], nomes: ["Syn Prop & Tech"], ambiguo: true },
  { tickers: ["TAEE11", "TAEE3", "TAEE4"], nomes: ["Taesa"] },
  { tickers: ["TASA3", "TASA4"], nomes: ["Taurus Armas", "Taurus"], ambiguo: true },
  { tickers: ["TCSA3"], nomes: ["Tecnisa"] },
  { tickers: ["TECN3"], nomes: ["Technos"], ambiguo: true },
  { tickers: ["TELB3", "TELB4"], nomes: ["Telebras"] },
  { tickers: ["TEND3"], nomes: ["Construtora Tenda", "Tenda"], ambiguo: true },
  { tickers: ["TFCO4"], nomes: ["Track & Field", "Track&Field"] },
  { tickers: ["TGMA3"], nomes: ["Tegma"] },
  { tickers: ["TIMS3"], nomes: ["TIM"] },
  { tickers: ["TKNO3", "TKNO4"], nomes: ["Tekno"], ambiguo: true },
  { tickers: ["TOTS3"], nomes: ["Totvs"] },
  { tickers: ["TPIS3"], nomes: ["Triunfo Participações"], ambiguo: true },
  { tickers: ["TRIS3"], nomes: ["Trisul"] },
  { tickers: ["TTEN3"], nomes: ["3tentos", "Três Tentos"] },
  { tickers: ["TUPY3"], nomes: ["Tupy"], ambiguo: true },
  { tickers: ["UCAS3"], nomes: ["Unicasa"] },
  { tickers: ["UGPA3"], nomes: ["Ultrapar"] },
  { tickers: ["UNIP3", "UNIP5", "UNIP6"], nomes: ["Unipar"] },
  { tickers: ["USIM3", "USIM5", "USIM6"], nomes: ["Usiminas"] },
  { tickers: ["VALE3"], nomes: ["Vale"], ambiguo: true, naoE: [/\bVale d(o|a|e|os|as)\b/, /\bVale (a pena|tudo|mais|perguntar)\b/i, /\bVale-/, /\bFundo Vale\b/, /\bVale (Europeu|BTG)\b/] },
  { tickers: ["VAMO3"], nomes: ["Vamos Locação", "Grupo Vamos"], ambiguo: true },
  { tickers: ["VBBR3"], nomes: ["Vibra Energia", "Vibra"], ambiguo: true },
  { tickers: ["VITT3"], nomes: ["Vittia"] },
  { tickers: ["VIVA3"], nomes: ["Vivara"] },
  { tickers: ["VIVR3"], nomes: ["Viver Incorporadora"], ambiguo: true },
  { tickers: ["VIVT3"], nomes: ["Telefônica Brasil", "Vivo"], ambiguo: true },
  { tickers: ["VLID3"], nomes: ["Valid Soluções", "Valid"], ambiguo: true },
  { tickers: ["VSTE3"], nomes: ["Veste S.A."], ambiguo: true },
  { tickers: ["VTRU3"], nomes: ["Vitru Educação", "Vitru"] },
  { tickers: ["VULC3"], nomes: ["Vulcabras"] },
  { tickers: ["VVEO3"], nomes: ["Viveo"] },
  { tickers: ["WDCN3"], nomes: ["WDC Networks"] },
  { tickers: ["WEGE3"], nomes: ["WEG"] },
  { tickers: ["WEST3"], nomes: ["Westwing"] },
  { tickers: ["WHRL3", "WHRL4"], nomes: ["Whirlpool"], ambiguo: true },
  { tickers: ["WIZC3"], nomes: ["Wiz Co"], ambiguo: true },
  { tickers: ["WLMM3", "WLMM4"], nomes: ["WLM"], ambiguo: true },
  { tickers: ["YDUQ3"], nomes: ["Yduqs", "Estácio"] },
  { tickers: ["ZAMP3"], nomes: ["Zamp", "Burger King Brasil"], ambiguo: true },
];

const POR_TICKER = new Map(EMPRESAS.flatMap((e) => e.tickers.map((t) => [t, e] as const)));

export function empresaDoTicker(ticker: string): EmpresaNaImprensa | undefined {
  return POR_TICKER.get(ticker);
}

/** Identidade do papel para a busca e o filtro, a partir da tabela escrita a mao. */
export function identidadeDoPapel(ticker: string): Identidade {
  const empresa = empresaDoTicker(ticker);
  if (!empresa) return { tickers: [ticker], nomes: [], ambiguo: false, naoEAEmpresa: [] };
  return {
    tickers: empresa.tickers,
    nomes: empresa.nomes,
    ambiguo: empresa.ambiguo === true,
    naoEAEmpresa: empresa.naoE ?? [],
  };
}
